site_name: CNR-INM MAO Research Group
site_description: Multidisciplinary Analysis & Optimization Research Group
site_url: https://cnr-inm-mao.github.io

theme:
  name: material

nav:
  - Home: index.md
  - Research: research.md
  - Software: software.md
  - Publications: publications.md
  - Contact: contact.md
