site_name: CNR-INM MAO Research Group
site_description: Multidisciplinary Analysis & Optimization Research Group

theme:
  name: material

nav:
  - Home: index.md
  - Research: research.md
  - People: people.md
  - Projects: projects.md
  - Software: software.md
  - Publications: publications.md
  - Datasets: datasets.md
  - Contact: contact.md
